### ISSUE TITLE
make check not working properly on mac

### ISSUE THREAD

**Issue by kikmon** [jbrandwood/huc#20]
the 'make check' command doesn't seem to properly process the list of files on Mac
According to the output, the mac version of md5sum is expecting an actual filename as a parameter and is confused by the '<' 
(this happens with and without the call to dos2unix)

Directly passing the file name to md5sum seems to be working, and only Win platform actually needs the file to be converted to UNIX format

**Comment by jbrandwood** [comment]
"make check" no longer uses md5sum ... closing this.
