### ISSUE TITLE
When compiling with the -sgx flag and invoking the assembler generate a .sgx file

### ISSUE THREAD

**Issue by pceDev16** [jbrandwood/huc#5]
Mainly an ease of use convention when compiling w huc and the -sgx flag, and then also invoking the pceas directly compiler by no using -s, produce a .sgx file by default instead of a .pce .

**Comment by jbrandwood** [comment]
While easy to implement, this change breaks existing build scripts, so I'm not sure that it's a good idea (although it really *should* work this way).

**Comment by jbrandwood** [comment]
Closing this!
